### ISSUE TITLE
Bad shadow at terminal

### ISSUE THREAD

**Issue by miguelcarax** [Antergos/Numix-Frost#23]
The problem is that the shadown looks bad at terminal.

![image](https://cloud.githubusercontent.com/assets/9194709/12391350/7d451fb4-bde7-11e5-8ac2-86b6dbcb6d9c.png)

**Comment by make-fun** [comment]
Great theme, thanks!
Having the same issue, and since I'm doing web development I had an idea what's going on...
The css box shadow blurring is simply cut off! It does not fade out before it reaches the edges of the surrounding div element.
![numix-shadowsprob1](https://cloud.githubusercontent.com/assets/17256162/13057665/fcb59638-d41d-11e5-949b-de3b4d606114.png)
(Try with your cursor. The transparent border, where you can grab the window is much wider on the left. This is where the shadow fades out just nicely. On the right it is cut of.)

@miguelcarax 
You can fix this with a user css file in your home .config (~/.config/gtk-3.0/gtk.css)
To remove the shadow use:
`
.window-frame{
	box-shadow: none;
}`
or reduce the shadow:
`
.window-frame{
	box-shadow: 1px 1px 5px 3px rgba(0,0,0,0.2);
}`
You need to restart gnome-shell after you have saved your gtk.css, hit "alt+f2" and type "r" in the box.
As to make this a bug fix in the master... well someone other may have to do this.
It's my first day on Gnome3 and Antergos...

Hope this helps
Cheers
