### ISSUE TITLE
[GTK 3.20]Thunderbird new task categories invisible

### ISSUE THREAD

**Issue by Bednar87** [Antergos/Numix-Frost#37]
Numix-frost-themes-3.5.r711

I am using XFCE. All packages updated to the latest versions.

DE: XFCE4
WM: Xfwm4
WM Theme: Numix-Frost
GTK Theme: Numix-Frost [GTK2]
Icon Theme: Numix-Circle
Font: Roboto 10

<a href="http://i.imgur.com/JEY9rRF.png">
  <img src="http://imgur.com/JEY9rRFl.png" />
</a>

Thanks,

B

**Comment by jeweloper** [comment]
I can confirm this behaviour.
But after some investigation I would say, it has to be fixed in lightning calendar.
It looks like they wrongly use the base text colour instead of the menu item colour for the category menu items.
In most of the gtk-themes you don't recognize it, because they use the same colour for base text and menu items. This is one of few uses black for the base text and white for menu items. 

Maybe you open a ticket in bugzilla.

As I understand it, thunderbird defines only a single gtk-widget for the whole (dialog) window. So it is not possible to customize a specific control within a gtk-theme.
As I know, it is the same with firefox and libreoffice.

**Comment by megax** [comment]
Numix: https://github.com/numixproject/numix-gtk-theme/issues/355

**Comment by megax** [comment]
@Bednar87 @jeweloper Still having trouble?

**Comment by jeweloper** [comment]
@megax The problem still exits with v3.6.4. But like I mentioned it could be a bug in lighning. However for now it's not present in bugzilla.
Maybe the bug will become obsolete with TB 47 and its GTK3 support?

**Comment by megax** [comment]
It is possible, I do not use the program =/

**Comment by Bednar87** [comment]
Still happening. I installed earlybird and the issue is still there.

**Comment by jeweloper** [comment]
I've submitted a bug report to bugzilla for this issue. [https://bugzilla.mozilla.org/show_bug.cgi?id=1305755](url)

**Comment by jeweloper** [comment]
The issue resolved in Thunderbird [f180e55bfcde](https://hg.mozilla.org/comm-central/rev/f180e55bfcde).

**Comment by Bednar87** [comment]
yup, just noticed. I will close this one here.
